version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "weekly"
    target-branch: "js-dependencies-from-package-json"

  - package-ecosystem: "npm"
    directory: "/lambda"
    schedule:
      interval: "weekly"
    target-branch: "js-dependencies-from-package-json"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
